model_type: "SW_HR"              # Choices: ["SW_HR", "LW_HR", "SW_FLUX", "LW_FLUX"]
learning_rate: 5.0e-3
folder: "simple_hr_energy"         # Folder to save the model
dev: False                  # Use development mode, loads less data
checkpoint: False          # Load checkpoint
weight_decay: 0           #1.0e-4
hidden_size: 150
batch_size: 256
seed: 3141
nn: "simple"
x_mode: "vertical"       # Choices: ["vertical", "horizontal"]
y_mode: "vertical"       # Choices: ["vertical", "horizontal"]
pretrained: False          # Load pretrained model
start_epoch: 0             # Start training from checkpoint
train_epochs: -1            # Train for E epochs use 0 for maximum + early stopping
eval_on: "test"            # Choices: ["train", "validation", "test"]
#exp_name: "icon-2.6.4_atm_amip-rad_R2B5_r1v1i1p2l1f1"
#base: "/work/bd1179/experiments/"
exp_name: "exp"
base: "path/to/data/"  # Base path to data
data: "data/"
train_path: "data/train_SW.zarr"
val_path: "data/val_SW.zarr"
test_path: "data/test_SW.zarr"
norm_file_path: "preprocessing/norm_file_extra.pkl"
vgrid_path: "path/to/vgrid.nc"
# Placeholder, will be set dynamically in Python
save_folder: ""
result_folder: ""
model_path: ""
grid: ""
vgrid: ""
pretrained_path: ""
checkpoint_path: ""
device: ""
num_gpus: 0
norm_file: ""
result_file: ""
x_shape: 0
y_shape: 0
extra_shape: 0
coarse_train: ""
coarse_val: ""
coarse_test: ""
train_steps: 0
validation_steps: 0


variables:
  in_vars:
    - "extra_3d_cli"      # Cloud ice content
    - "extra_3d_clw"      # Cloud liquid water content
    - "extra_3d_hus"      # Specific humidity
    - "toa"               # Top of atmosphere
    - "extra_2d_albedo"   # Surface albedo
    - "o3"                # Ozone concentration
    - "cl"                # Cloud fraction
    - "rho"               # Air density
    - "extra_3d_ta"       # Air temperature
  out_vars:
    - "tend_ta_rsw"       # Tendency of air temperature due to shortwave radiation
  extra_in:
    - "q"                 # Total water content hus + cli + clw
    - "qconv"             # Conversion factor for W/m^2 to K/day
    - "rsds"              # Surface downwelling shortwave radiation
    - "rsut"              # Top of atmosphere upwelling shortwave radiation
  diagnostics:
    - "extra_2d_prw"      # Precipitable water
    - "extra_2d_clivi"    # Vertically integrated cloud ice
    - "extra_2d_cllvi"    # Vertically integrated cloud liquid
    - "extra_3d_pfull"    # Full pressure level
    - "clt"               # Total cloud cover
